services:
  qdrant_service:
    container_name: qdrant_container
    image: qdrant/qdrant
    # image: skkzsh/qdrant
    # build: .
    ports:
      - "6333:6333"
      - "6334:6334"
    environment:
      TZ: Asia/Tokyo
    volumes:
      - $PWD/storage:/qdrant/storage
