version: "3"
services:
  redis_service:
    container_name: redis_container
    image: redis/redis-stack-server
    # image: skkzsh/redis-stack-server
    # build: .
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Tokyo
    volumes:
      - $PWD/data:/data
